---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/articles
  label: Articles
  create: documents
  match: "**/*"
  templates:
  - article
- type: document
  path: content/featured/_index.md
  label: Featured
  templates:
  - featured
- type: directory
  path: content/authors
  label: Authors
  create: documents
  match: "**/*"
  templates:
  - author
- type: directory
  path: content/scene/companies
  label: Companies
  create: documents
  match: "**/*"
  templates:
  - company
- type: directory
  path: content/scene/people
  label: People
  create: documents
  match: "**/*"
  templates:
  - person
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
upload_dir: media
public_path: https://res.cloudinary.com/schmopera/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_env:
  - HUGO_ENV=Staging
  - HUGO_VERSION=0.52
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.52'
